version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: musga-postgres
    environment:
      POSTGRES_DB: musga
      POSTGRES_USER: musga
      POSTGRES_PASSWORD: musga123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: musga-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: